# -*- coding: utf-8 -*-
"""solar_irradiation_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2scbrVqkgxWZEbXWsTS30ovNRF0ZvmJ

# Solar Irradiation Analysis in Houston Zones

#### This notebook calculates annual solar irradiation (kWh/m²), and average daily solar peak hours (HSP) using the PVGIS API for selected neighborhoods in the Houston area
"""

import requests
import pandas as pd

#Define Houston zones
zones = {
    "Midtown": (29.7411, -95.3739),
    "Downtown": (29.7589,-95.3677),
    "Uptown/Galleria" : (29.7477,-95.4613),
    "West University" : (29.7174, -95.4285),
    "Third Ward": (29.7230, -95.3625),
    "Museum District" : (29.7253, -95.3906),
    "EaDo" : (29.7523, -95.3422),
    "The Heights" : (29.7671, -95.3992),
    "Rice Military" : (29.7671,-95.4167),
    "Montrose" : (29.7446, -95.3904)
}

#API base URL
API_BASE = "https://re.jrc.ec.europa.eu/api/v5_2/PVcalc"

# Base parameters for all requests
params_base = {
    "peakpower": 1,
    "loss": 14,
    "angle": 30,
    "aspect": 0,
    "outputformat": "json",
    "optimalangles": 1,
    "usehorizon": 1,
    "pvcalculation": 1
}

results = [] #Store results

for zone, (lat, lon) in zones.items():
    params = params_base.copy()
    params["lat"]= lat
    params["lon"] = lon
    response = requests.get(API_BASE, params=params)
    if response.status_code== 200:
      data = response.json()

      try:
        annual_irrad = data['outputs']['totals']['fixed']['E_y'] #Annual irradiation
        hsp_daily = round(annual_irrad/365,2) #Average daily HSP
        results.append({
            "Zone": zone,
            "Latitude": lat,
            "Longitude" : lon,
            "Annual Irradiation (kWh/m²)" : annual_irrad,
            "Daily Solar Peak Hours(HSP)": hsp_daily
        })

      except KeyError:
        print(f"Missing data for {zone}")
    else:
      print(f"Failed to get data for {zone})")

# Convert results to DataFrame
df = pd.DataFrame(results)
df

df.to_csv("solar_irradiation_houston_zones.csv", index=False) #CSV exported

!ls